model = "gpt-5.1-codex-max"
approval_policy = "never"
sandbox_mode = "danger-full-access"
model_reasoning_effort = "xhigh"

[features]
web_search_request = true
streamable_shell = true

[tui]
notifications = true

[notice]
"hide_gpt-5.1-codex-max_migration_prompt" = true
